-- MY_USER.TECH_LOGS definition

CREATE TABLE "MY_USER"."TECH_LOGS" 
(
    "ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
	"JOB_ID" NUMBER(15,0), 
	"SCHEMA_NM" VARCHAR2(50), 
	"PARAM_NM" VARCHAR2(200), 
	"PROC_NM" VARCHAR2(50), 
	"STEP_NM" VARCHAR2(100), 
	"STATUS_NM" VARCHAR2(2000), 
	"RUN_START_DTTM" TIMESTAMP (6), 
	"RUN_END_DTTM" TIMESTAMP (6), 
	"RUN_ALL_DTTM" INTERVAL DAY (2) TO SECOND (6), 
	"ROW_CNT" NUMBER(30,0), 
	 PRIMARY KEY ("ID")
) SEGMENT CREATION IMMEDIATE
  TABLESPACE "USERS" ;
