-- MY_USER.TEST_FULL definition

CREATE TABLE "MY_USER"."TEST_FULL" 
(
    "JOB_ID" NUMBER(15,0),
	"ID" NUMBER(10,0), 
	"TEXT" VARCHAR2(200), 
	"CREATE_DTTM" TIMESTAMP (6), 
	"DRP_BATCH_ID" NUMBER(10,0) GENERATED ALWAYS AS (MOD("ID",10)) VIRTUAL 
)
    PARTITION BY LIST ("JOB_ID") AUTOMATIC
    (PARTITION "P0"  VALUES (0) SEGMENT CREATION DEFERRED)
PARALLEL;
